name: torrent_task
description: BitTorrent download client package written by pure Dart language.
version: 0.3.0
repository: https://github.com/eclipseglory/torrent_task
issue_tracker : https://github.com/eclipseglory/torrent_task/issues
publish_to: https://pub.dev/

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
#  path: ^1.7.0
  torrent_model:
    git: https://github.com/xhns/torrent_model.git
  torrent_tracker:
    git: https://github.com/xhns/torrent_tracker.git
  
  # torrent_tracker: 
  #   path: '../../dd/torrent_tracker'

  dht_dart:
    git: https://github.com/xhns/dht.git
  dartorrent_common:
    git: https://github.com/xhns/dartorrent_common.git
  bencode_dart :
    git: https://github.com/xhns/bencode_dart.git
  utp:
    git: https://github.com/xhns/utp.git
  # utp:
  #   path: '../../dd/utp'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
