name: torrent_task
description: BitTorrent download client package written by pure Dart language.
version: 0.3.0
repository: https://github.com/eclipseglory/torrent_task
issue_tracker : https://github.com/eclipseglory/torrent_task/issues
publish_to: https://pub.dev/

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
#  path: ^1.7.0
  torrent_model:
    path: ../torrent_model
  torrent_tracker:
    path: ../torrent_tracker
  
  # torrent_tracker: 
  #   path: '../../dd/torrent_tracker'

  dht_dart:
    path: ../dht
  dartorrent_common:
    path: ../dartorrent_common
  bencode_dart :
    path: ../bencode_dart
  utp:
    path: ../utp
  # utp:
  #   path: '../../dd/utp'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
