name: torrent_task
description: BitTorrent download client package written by pure Dart language.
version: 0.3.0
repository: https://github.com/eclipseglory/torrent_task
issue_tracker : https://github.com/eclipseglory/torrent_task/issues
publish_to: https://pub.dev/

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
#  path: ^1.7.0
  torrent_model:
    git:
      url: https://github.com/PURUSHOTHAM-REDDY-N/torrent_model.git
      ref: master 
  torrent_tracker:
    git:
      url: https://github.com/PURUSHOTHAM-REDDY-N/torrent_tracker.git
      ref: master 
  
  # torrent_tracker: 
  #   path: '../../dd/torrent_tracker'

  dht_dart:
    git:
      url: https://github.com/PURUSHOTHAM-REDDY-N/dht_dart.git
      ref: main 
  dartorrent_common:
    git:
      url: https://github.com/PURUSHOTHAM-REDDY-N/dartorrent_common.git
      ref: main 
  bencode_dart :
    git:
      url: https://github.com/PURUSHOTHAM-REDDY-N/bencode_dart.git
      ref: master 
  utp:
    git:
      url: https://github.com/PURUSHOTHAM-REDDY-N/utp.git
      ref: main 
  # utp:
  #   path: '../../dd/utp'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
